# erueka客户端配置
eureka:
  client:
    service-url:
      defaultZone: http://register.leyou.com/eureka
server:
  port: 9090
spring:
  application:
    name: leyou-gateway

# zuul配置
zuul:
  routes:
    leyou-item: /item/**
    leyou-search: /search/**
    leyou-user-server: /user/**
    leyou-auth-server: /auth/**
  prefix: /api
  ignored-services: leyou-upload
  add-host-header: true
  sensitive-headers:

leyou:
  jwt:
    pubKeyPath:  D:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LEYOUTOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item