server:
  port: 8083
spring:
  application:
    name: leyou-search
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.14:9300
eureka:
  client:
    service-url:
      defaultZone: http://register.leyou.com/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
#
#circuitBreaker:
#  requestVolumeThreshold: 5  #请求次数
#  sleepWindowInMilliseconds: 10000  #休眠时长
#  errorThresholdPercentage: 50  #失败占比

feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true # 开启请求压缩
    response:
      enabled: true # 开启响应压缩