server:
  port: 7070
spring:
  application:
    name: leyou-item
  datasource:
    url: jdbc:mysql:///jingtest
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://register.leyou.com/eureka
